/**
 * Icon lookup by name.
 *
 * Icons are lucide (https://lucide.dev). Older app configs store legacy icon
 * names (`AppstoreOutlined`, `SettingFilled`, …); {@link resolveIcon} maps
 * those to the closest lucide icon so existing menus, buttons and steps keep
 * their icons.
 */
import React from 'react';
import { icons, type LucideIcon, type LucideProps } from 'lucide-react';

export type { LucideIcon, LucideProps };

/** Every lucide icon name, for pickers. */
export const iconNames = Object.keys(icons).sort();

/** Legacy base names (suffix stripped) whose lucide name differs. */
const legacy: Record<string, string> = {
  Account: 'CircleUser',
  AccountBook: 'NotebookTabs',
  Alert: 'TriangleAlert',
  Alipay: 'Wallet',
  Aliwangwang: 'MessageCircle',
  Api: 'Plug',
  Appstore: 'LayoutGrid',
  AppstoreAdd: 'LayoutGrid',
  Audio: 'Mic',
  Bank: 'Landmark',
  BarChart: 'ChartColumn',
  Bars: 'Menu',
  Bell: 'Bell',
  Block: 'Ban',
  Book: 'BookOpen',
  Border: 'Square',
  Branches: 'GitBranch',
  Bug: 'Bug',
  Build: 'Hammer',
  Bulb: 'Lightbulb',
  Calculator: 'Calculator',
  Calendar: 'Calendar',
  Camera: 'Camera',
  Car: 'Car',
  CaretDown: 'ChevronDown',
  CaretLeft: 'ChevronLeft',
  CaretRight: 'ChevronRight',
  CaretUp: 'ChevronUp',
  CarryOut: 'CalendarCheck',
  Check: 'Check',
  CheckCircle: 'CircleCheck',
  CheckSquare: 'SquareCheck',
  ClockCircle: 'Clock',
  Close: 'X',
  CloseCircle: 'CircleX',
  CloseSquare: 'SquareX',
  Cloud: 'Cloud',
  CloudDownload: 'CloudDownload',
  CloudServer: 'Server',
  CloudSync: 'RefreshCw',
  CloudUpload: 'CloudUpload',
  Cluster: 'Network',
  Code: 'Code',
  Comment: 'MessageSquare',
  Compass: 'Compass',
  Compress: 'Shrink',
  Contacts: 'Contact',
  Container: 'Container',
  Control: 'SlidersHorizontal',
  Copy: 'Copy',
  Copyright: 'Copyright',
  CreditCard: 'CreditCard',
  Crown: 'Crown',
  CustomerService: 'Headphones',
  Dashboard: 'Gauge',
  Database: 'Database',
  Delete: 'Trash',
  DeleteRow: 'Trash',
  DeploymentUnit: 'Boxes',
  Desktop: 'Monitor',
  Dingding: 'MessageCircle',
  Disconnect: 'Unplug',
  Dislike: 'ThumbsDown',
  Dollar: 'DollarSign',
  DollarCircle: 'CircleDollarSign',
  DoubleLeft: 'ChevronsLeft',
  DoubleRight: 'ChevronsRight',
  Down: 'ChevronDown',
  DownCircle: 'CircleChevronDown',
  Download: 'Download',
  Drag: 'GripVertical',
  Edit: 'Pencil',
  Ellipsis: 'Ellipsis',
  Enter: 'CornerDownLeft',
  Environment: 'MapPin',
  Euro: 'Euro',
  Exception: 'FileExclamationPoint',
  Exclamation: 'CircleAlert',
  ExclamationCircle: 'CircleAlert',
  Expand: 'Expand',
  Experiment: 'FlaskConical',
  Export: 'Upload',
  Eye: 'Eye',
  EyeInvisible: 'EyeOff',
  Fall: 'TrendingDown',
  FieldTime: 'Timer',
  File: 'File',
  FileAdd: 'FilePlus',
  FileDone: 'FileCheck',
  FileExcel: 'FileSpreadsheet',
  FileImage: 'FileImage',
  FileMarkdown: 'FileCode',
  FilePdf: 'FileText',
  FileProtect: 'FileLock',
  FileSearch: 'FileSearch',
  FileText: 'FileText',
  FileUnknown: 'FileQuestionMark',
  FileWord: 'FileText',
  FileZip: 'FileArchive',
  Filter: 'Funnel',
  Fire: 'Flame',
  Flag: 'Flag',
  Folder: 'Folder',
  FolderAdd: 'FolderPlus',
  FolderOpen: 'FolderOpen',
  Form: 'ClipboardList',
  Fullscreen: 'Maximize',
  FullscreenExit: 'Minimize',
  Function: 'SquareFunction',
  Fund: 'ChartLine',
  Gift: 'Gift',
  Github: 'GitFork',
  Global: 'Globe',
  Gold: 'Coins',
  Heart: 'Heart',
  History: 'RotateCcwClock',
  Home: 'House',
  Hourglass: 'Hourglass',
  Idcard: 'IdCard',
  Import: 'Download',
  Inbox: 'Inbox',
  Info: 'Info',
  InfoCircle: 'Info',
  Insurance: 'ShieldCheck',
  Key: 'Key',
  Laptop: 'Laptop',
  Layout: 'LayoutPanelTop',
  Left: 'ChevronLeft',
  LeftCircle: 'CircleChevronLeft',
  Like: 'ThumbsUp',
  LineChart: 'ChartLine',
  Link: 'Link',
  Loading: 'LoaderCircle',
  Lock: 'Lock',
  Login: 'LogIn',
  Logout: 'LogOut',
  Mail: 'Mail',
  Man: 'User',
  Medicine: 'Pill',
  Menu: 'Menu',
  MenuFold: 'PanelLeftClose',
  MenuUnfold: 'PanelLeftOpen',
  Message: 'MessageSquare',
  Minus: 'Minus',
  MinusCircle: 'CircleMinus',
  MinusSquare: 'SquareMinus',
  Mobile: 'Smartphone',
  MoneyCollect: 'Banknote',
  More: 'Ellipsis',
  Notification: 'Megaphone',
  OrderedList: 'ListOrdered',
  PaperClip: 'Paperclip',
  Partition: 'Network',
  Pause: 'Pause',
  PauseCircle: 'CirclePause',
  PayCircle: 'CircleDollarSign',
  Percentage: 'Percent',
  Phone: 'Phone',
  PicCenter: 'Image',
  Picture: 'Image',
  PieChart: 'ChartPie',
  PlayCircle: 'CirclePlay',
  Plus: 'Plus',
  PlusCircle: 'CirclePlus',
  PlusSquare: 'SquarePlus',
  Pound: 'PoundSterling',
  Poweroff: 'Power',
  Printer: 'Printer',
  Profile: 'IdCard',
  Project: 'FolderKanban',
  PropertySafety: 'ShieldCheck',
  PushpinFilled: 'Pin',
  Pushpin: 'Pin',
  Qrcode: 'QrCode',
  Question: 'CircleQuestionMark',
  QuestionCircle: 'CircleQuestionMark',
  Read: 'BookOpen',
  Reconciliation: 'ClipboardCheck',
  Redo: 'Redo',
  Reload: 'RotateCw',
  Rest: 'Coffee',
  Retweet: 'Repeat',
  Right: 'ChevronRight',
  RightCircle: 'CircleChevronRight',
  Rise: 'TrendingUp',
  Robot: 'Bot',
  Rocket: 'Rocket',
  RotateLeft: 'RotateCcw',
  RotateRight: 'RotateCw',
  Safety: 'Shield',
  SafetyCertificate: 'ShieldCheck',
  Save: 'Save',
  Scan: 'ScanLine',
  Schedule: 'CalendarClock',
  Search: 'Search',
  Security: 'ShieldCheck',
  Select: 'MousePointerClick',
  Send: 'Send',
  Setting: 'Settings',
  Shake: 'Vibrate',
  Share: 'Share2',
  Shop: 'Store',
  Shopping: 'ShoppingBag',
  ShoppingCart: 'ShoppingCart',
  Skin: 'Shirt',
  Smile: 'FaceSlightlySmiling',
  Solution: 'ClipboardList',
  Sound: 'Volume2',
  Star: 'Star',
  Stop: 'OctagonX',
  Swap: 'ArrowLeftRight',
  Sync: 'RefreshCw',
  Table: 'Table',
  Tablet: 'Tablet',
  Tag: 'Tag',
  Tags: 'Tags',
  Team: 'Users',
  Thunderbolt: 'Zap',
  Tool: 'Wrench',
  Trademark: 'Award',
  Transaction: 'ArrowLeftRight',
  Trophy: 'Trophy',
  Unlock: 'LockOpen',
  UnorderedList: 'List',
  Up: 'ChevronUp',
  UpCircle: 'CircleChevronUp',
  Upload: 'Upload',
  Usb: 'Usb',
  User: 'User',
  UserAdd: 'UserPlus',
  UserDelete: 'UserMinus',
  UserSwitch: 'UserCog',
  Usergroup: 'Users',
  UsergroupAdd: 'UserPlus',
  VerticalLeft: 'ArrowLeftToLine',
  VerticalRight: 'ArrowRightToLine',
  VideoCamera: 'Video',
  Wallet: 'Wallet',
  Warning: 'TriangleAlert',
  Wechat: 'MessageCircle',
  Wifi: 'Wifi',
  Woman: 'User',
  ZoomIn: 'ZoomIn',
  ZoomOut: 'ZoomOut',
};

const iconMap = icons as Record<string, LucideIcon>;

/**
 * Resolve an icon name — a lucide name (`Settings`, `settings`) or a legacy
 * legacy name (`SettingOutlined`) — to a component. Unknown names give
 * `undefined`.
 */
export function resolveIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined;
  if (iconMap[name]) return iconMap[name];
  // kebab-case (`chevron-down`) → PascalCase
  const pascal = name.replace(/(^|[-_ ])(\w)/g, (_m, _s, c: string) => c.toUpperCase());
  if (iconMap[pascal]) return iconMap[pascal];
  const base = pascal.replace(/(Outlined|Filled|TwoTone)$/, '');
  const mapped = legacy[base];
  if (mapped && iconMap[mapped]) return iconMap[mapped];
  return iconMap[base];
}

export interface NamedIconProps extends LucideProps {
  name?: string | null;
  /** Spin the icon (e.g. a refresh or loading glyph). */
  spin?: boolean;
}

/**
 * Render an icon by name. Sized to the surrounding text (`1em`) unless a
 * `size` is given, so it drops into buttons and labels like a glyph.
 */
export function NamedIcon({ name, spin, className, size = '1em', ...rest }: NamedIconProps) {
  const Icon = resolveIcon(name);
  if (!Icon) return null;
  return <Icon size={size} aria-hidden="true" className={[spin ? 'animate-spin' : '', 'shrink-0', className || ''].join(' ').trim()} {...rest} />;
}
